--- 
- 
  name: "install flask "
  pip: 
    name: "{{ item }}"
  with_items: 
    - flask
    - flask-mysql
- 
  copy: "src=app.py    dest=/opt/app.py"
  name: 拷贝源码到目标服务器

-
  name: 启动web服务
  shell: "FLASK_APP=app.py nohup flask run --host=0.0.0.0   &"
